### PR TITLE
Error in IndexManagement when app can't create lazy index on 3rd step

### PR DESCRIPTION
**Pull request by SychevIgor**
looks like small typo 

Error in IndexManagement when app can't create lazy index on 3rd step

### CODE REVIEW

**Comment by SychevIgor** [comment]
Ping... 11 days without answers

**Comment by rnagpal** [comment]
@SychevIgor Sorry for the delay in looking at this PR. I believe the reason to keep the Newtonsoft version to 6.0.8 is that we publish this version as our dependency and we test our code with this version. Most likely, version 9.0 should be backward compatible but we have seen breaking changes, so we want to stick with the version we have tested. Also given that this is a sample project with this Newtonsoft version installed locally to the project, it shouldn't effect anything outside this. Please let me know if that's blocking you in any way to use version 6.0.8.

If you could limit the changes to updating the .NET SDK to 1.12 and fixing the collectionId issue, I can merge this PR. 

/cc: arramac

**Comment by SychevIgor** [comment]
Hi, we have 2 different PR, in one we have only fix, in another update...
Also, I tested all samples with sdk 1.12 and it's compatible with newtonsoft 9.*

**Comment by rnagpal** [comment]
@SychevIgor I saw the 2 PRs and they both seem to be same(contain the fix as well as update). If you could separate the indexing fix and update SDK to 1.12.0, I'll merge it now.

For the Newtonsoft version, our samples may not cover the full functionality and are intended for sample purpose only. We will consider updating the Newtonsoft version in future. Is this something that is blocking you?

**Comment by SychevIgor** [comment]
Ok, find that after I did a pull request in the same branch I did one more commit and GitHub update my pull request.
now we have only 1 commit in this PR. I think we can continuer discussing about packages update in another PR

**Pull request merged**
