### PR TITLE
Refactoring shared utilities.

### PR DESCRIPTION
**Pull request by serkanpektas**
*Removing redundant using directives.
*Removing redundant type arguments.
*Removing redundant type specification
*Removing unused local variables.
*Using simple 'var' types.
*Changing <V> to <TValue>.
*Adding Null check expression for StatusCode of DocumentClientException.
*Preventing access to modified closure.
*Adding missing xml-doc comments.
*Removing redundant initializer and moving to.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@serkanpektas__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@serkanpektas__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by ryancrawcour** [comment]
what changes did you make? I see a bunch of typed variables changed to var, but that's mostly it?

**Comment by serkanpektas** [comment]
i have updated the description.

**Pull request closed without merging**
